import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@core/theme";
import { Header } from "@core/header";
import { ApolloWrapper } from "@core/graphql";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ApolloWrapper>
            <Header />
            {children}
          </ApolloWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
