import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@core/theme";
import { Header } from "@core/header";
import { ApolloWrapper } from "@core/graphql";
import { AuthContext } from "@core/auth";
import { logString } from "kubrick-code-npm-test";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  logString("RootLayout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthContext>
            <ApolloWrapper>
              <Header />
              {children}
            </ApolloWrapper>
          </AuthContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
