on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Notify slack for new version deployment
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_API_URL: "https://slack.com/api/chat.postMessage"
          SLACK_CHANNEL: "#log-test"
        run: |
          curl -X POST -H "Authorization: Bearer $SLACK_API_TOKEN" -H "Content-Type: application/json" \
          -d "{
                \"channel\": \"$SLACK_CHANNEL\",
                \"text\": \"새 버전이 배포되었습니다.\"
              }" \
          $SLACK_API_URL